### ISSUE TITLE
Erro ao executar "sudo ionic serve"

### ISSUE THREAD

**Issue by jowbjj** [sobreirami/AppEconomiaMaxima#1]
Ola parceiro, ao executar o comando "sudo ionic serve" informa o seguinte erro:

tslint: src/pages/perfil/perfil.ts, line: 4 
            Unused import: 'Transfer' 

       L3:    Platform, LoadingController, Loading } from 'ionic-angular';
       L4:  import { Camera, File, Transfer, FilePath } from 'ionic-native';
       L5:  import { DbUsuarios } from '../../providers/db-usuarios'

Essa e a versao que estou utilizando:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0-beta.3
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.7.1
Xcode version: Xcode 8.2.1 Build version 8C1002

Abraco.

**Comment by sobreirami** [comment]
ionic plugin add cordova-plugin-file-transfer

Para mais informações
https://ionicframework.com/docs/v2/native/transfer/
